name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install --immutable --check-cache
      - run: yarn hardhat compile
      - run: yarn test
      - run: yarn lint
      - run: yarn build
